spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: productModule
        uri: http://localhost:8901/
        predicates:
        - Path=/product/**
      - id: stockModule
        uri: http://localhost:8900/
        predicates:
        - Path=/stock/**
            
server:
  port: 8080



