server:
  port: 8080


spring:
  application:
    name: ProductCommandService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productCommandDB
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin